package com.webserver.bean;
// Generated 15-jun-2015 20:55:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCliente generated by hbm2java
 */
@Entity
@Table(name="tb_cliente"
    ,catalog="abcdatabase"
)
public class TbCliente  implements java.io.Serializable {


     private int inIdcliente;
     private TbTipocliente tbTipocliente;
     private String vcNombres;
     private String vcApellidopa;
     private String vcApellidoma;
     private String vcTelefono;
     private String vcMovil;
     private Date dtFecharegistro;
     private Date dtUltimoingreso;
     private Integer inNumerointentos;
     private long inDni;
     private Integer inEstado;
     private Set tbCuentas = new HashSet(0);
     private Set tbLogclientes = new HashSet(0);

    public TbCliente() {
    }

	
    public TbCliente(int inIdcliente, TbTipocliente tbTipocliente, Date dtFecharegistro, Date dtUltimoingreso, long inDni) {
        this.inIdcliente = inIdcliente;
        this.tbTipocliente = tbTipocliente;
        this.dtFecharegistro = dtFecharegistro;
        this.dtUltimoingreso = dtUltimoingreso;
        this.inDni = inDni;
    }
    public TbCliente(int inIdcliente, TbTipocliente tbTipocliente, String vcNombres, String vcApellidopa, String vcApellidoma, String vcTelefono, String vcMovil, Date dtFecharegistro, Date dtUltimoingreso, Integer inNumerointentos, long inDni, Integer inEstado, Set tbCuentas, Set tbLogclientes) {
       this.inIdcliente = inIdcliente;
       this.tbTipocliente = tbTipocliente;
       this.vcNombres = vcNombres;
       this.vcApellidopa = vcApellidopa;
       this.vcApellidoma = vcApellidoma;
       this.vcTelefono = vcTelefono;
       this.vcMovil = vcMovil;
       this.dtFecharegistro = dtFecharegistro;
       this.dtUltimoingreso = dtUltimoingreso;
       this.inNumerointentos = inNumerointentos;
       this.inDni = inDni;
       this.inEstado = inEstado;
       this.tbCuentas = tbCuentas;
       this.tbLogclientes = tbLogclientes;
    }
   
     @Id 

    
    @Column(name="IN_IDCLIENTE", unique=true, nullable=false)
    public int getInIdcliente() {
        return this.inIdcliente;
    }
    
    public void setInIdcliente(int inIdcliente) {
        this.inIdcliente = inIdcliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TB_TIPOCLIENTE_IN_IDTIPO", nullable=false)
    public TbTipocliente getTbTipocliente() {
        return this.tbTipocliente;
    }
    
    public void setTbTipocliente(TbTipocliente tbTipocliente) {
        this.tbTipocliente = tbTipocliente;
    }

    
    @Column(name="VC_NOMBRES", length=45)
    public String getVcNombres() {
        return this.vcNombres;
    }
    
    public void setVcNombres(String vcNombres) {
        this.vcNombres = vcNombres;
    }

    
    @Column(name="VC_APELLIDOPA", length=45)
    public String getVcApellidopa() {
        return this.vcApellidopa;
    }
    
    public void setVcApellidopa(String vcApellidopa) {
        this.vcApellidopa = vcApellidopa;
    }

    
    @Column(name="VC_APELLIDOMA", length=45)
    public String getVcApellidoma() {
        return this.vcApellidoma;
    }
    
    public void setVcApellidoma(String vcApellidoma) {
        this.vcApellidoma = vcApellidoma;
    }

    
    @Column(name="VC_TELEFONO", length=10)
    public String getVcTelefono() {
        return this.vcTelefono;
    }
    
    public void setVcTelefono(String vcTelefono) {
        this.vcTelefono = vcTelefono;
    }

    
    @Column(name="VC_MOVIL", length=9)
    public String getVcMovil() {
        return this.vcMovil;
    }
    
    public void setVcMovil(String vcMovil) {
        this.vcMovil = vcMovil;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FECHAREGISTRO", nullable=false, length=10)
    public Date getDtFecharegistro() {
        return this.dtFecharegistro;
    }
    
    public void setDtFecharegistro(Date dtFecharegistro) {
        this.dtFecharegistro = dtFecharegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMOINGRESO", nullable=false, length=10)
    public Date getDtUltimoingreso() {
        return this.dtUltimoingreso;
    }
    
    public void setDtUltimoingreso(Date dtUltimoingreso) {
        this.dtUltimoingreso = dtUltimoingreso;
    }

    
    @Column(name="IN_NUMEROINTENTOS")
    public Integer getInNumerointentos() {
        return this.inNumerointentos;
    }
    
    public void setInNumerointentos(Integer inNumerointentos) {
        this.inNumerointentos = inNumerointentos;
    }

    
    @Column(name="IN_DNI", nullable=false)
    public long getInDni() {
        return this.inDni;
    }
    
    public void setInDni(long inDni) {
        this.inDni = inDni;
    }

    
    @Column(name="IN_ESTADO")
    public Integer getInEstado() {
        return this.inEstado;
    }
    
    public void setInEstado(Integer inEstado) {
        this.inEstado = inEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCliente")
    public Set getTbCuentas() {
        return this.tbCuentas;
    }
    
    public void setTbCuentas(Set tbCuentas) {
        this.tbCuentas = tbCuentas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCliente")
    public Set getTbLogclientes() {
        return this.tbLogclientes;
    }
    
    public void setTbLogclientes(Set tbLogclientes) {
        this.tbLogclientes = tbLogclientes;
    }




}


