package com.webserver.bean;
// Generated 15-jun-2015 20:55:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbLogcliente generated by hbm2java
 */
@Entity
@Table(name="tb_logcliente"
    ,catalog="abcdatabase"
)
public class TbLogcliente  implements java.io.Serializable {


     private int inIdlog;
     private TbCliente tbCliente;
     private Date dtFechaultlogin;
     private Date dtUltimologin;
     private Date dtUltimaconsulta;

    public TbLogcliente() {
    }

	
    public TbLogcliente(int inIdlog, TbCliente tbCliente) {
        this.inIdlog = inIdlog;
        this.tbCliente = tbCliente;
    }
    public TbLogcliente(int inIdlog, TbCliente tbCliente, Date dtFechaultlogin, Date dtUltimologin, Date dtUltimaconsulta) {
       this.inIdlog = inIdlog;
       this.tbCliente = tbCliente;
       this.dtFechaultlogin = dtFechaultlogin;
       this.dtUltimologin = dtUltimologin;
       this.dtUltimaconsulta = dtUltimaconsulta;
    }
   
     @Id 

    
    @Column(name="IN_IDLOG", unique=true, nullable=false)
    public int getInIdlog() {
        return this.inIdlog;
    }
    
    public void setInIdlog(int inIdlog) {
        this.inIdlog = inIdlog;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TB_CLIENTE_IN_IDCLIENTE", nullable=false)
    public TbCliente getTbCliente() {
        return this.tbCliente;
    }
    
    public void setTbCliente(TbCliente tbCliente) {
        this.tbCliente = tbCliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FECHAULTLOGIN", length=10)
    public Date getDtFechaultlogin() {
        return this.dtFechaultlogin;
    }
    
    public void setDtFechaultlogin(Date dtFechaultlogin) {
        this.dtFechaultlogin = dtFechaultlogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_ULTIMOLOGIN", length=19)
    public Date getDtUltimologin() {
        return this.dtUltimologin;
    }
    
    public void setDtUltimologin(Date dtUltimologin) {
        this.dtUltimologin = dtUltimologin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_ULTIMACONSULTA", length=19)
    public Date getDtUltimaconsulta() {
        return this.dtUltimaconsulta;
    }
    
    public void setDtUltimaconsulta(Date dtUltimaconsulta) {
        this.dtUltimaconsulta = dtUltimaconsulta;
    }




}


