package com.webserver.bean;
// Generated 15-jun-2015 20:55:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbTipocliente generated by hbm2java
 */
@Entity
@Table(name="tb_tipocliente"
    ,catalog="abcdatabase"
)
public class TbTipocliente  implements java.io.Serializable {


     private int inIdtipo;
     private String vcNombretipo;
     private String vcDescripciontipo;
     private Set tbClientes = new HashSet(0);

    public TbTipocliente() {
    }

	
    public TbTipocliente(int inIdtipo, String vcNombretipo) {
        this.inIdtipo = inIdtipo;
        this.vcNombretipo = vcNombretipo;
    }
    public TbTipocliente(int inIdtipo, String vcNombretipo, String vcDescripciontipo, Set tbClientes) {
       this.inIdtipo = inIdtipo;
       this.vcNombretipo = vcNombretipo;
       this.vcDescripciontipo = vcDescripciontipo;
       this.tbClientes = tbClientes;
    }
   
     @Id 

    
    @Column(name="IN_IDTIPO", unique=true, nullable=false)
    public int getInIdtipo() {
        return this.inIdtipo;
    }
    
    public void setInIdtipo(int inIdtipo) {
        this.inIdtipo = inIdtipo;
    }

    
    @Column(name="VC_NOMBRETIPO", nullable=false, length=45)
    public String getVcNombretipo() {
        return this.vcNombretipo;
    }
    
    public void setVcNombretipo(String vcNombretipo) {
        this.vcNombretipo = vcNombretipo;
    }

    
    @Column(name="VC_DESCRIPCIONTIPO", length=45)
    public String getVcDescripciontipo() {
        return this.vcDescripciontipo;
    }
    
    public void setVcDescripciontipo(String vcDescripciontipo) {
        this.vcDescripciontipo = vcDescripciontipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbTipocliente")
    public Set getTbClientes() {
        return this.tbClientes;
    }
    
    public void setTbClientes(Set tbClientes) {
        this.tbClientes = tbClientes;
    }




}


