package com.webserver.bean;
// Generated 15-jun-2015 20:55:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbTipocuenta generated by hbm2java
 */
@Entity
@Table(name="tb_tipocuenta"
    ,catalog="abcdatabase"
)
public class TbTipocuenta  implements java.io.Serializable {


     private int inIdtipocuenta;
     private String vcNombretipocta;
     private String vcDescripciontipocta;
     private Set tbCuentas = new HashSet(0);

    public TbTipocuenta() {
    }

	
    public TbTipocuenta(int inIdtipocuenta, String vcNombretipocta) {
        this.inIdtipocuenta = inIdtipocuenta;
        this.vcNombretipocta = vcNombretipocta;
    }
    public TbTipocuenta(int inIdtipocuenta, String vcNombretipocta, String vcDescripciontipocta, Set tbCuentas) {
       this.inIdtipocuenta = inIdtipocuenta;
       this.vcNombretipocta = vcNombretipocta;
       this.vcDescripciontipocta = vcDescripciontipocta;
       this.tbCuentas = tbCuentas;
    }
   
     @Id 

    
    @Column(name="IN_IDTIPOCUENTA", unique=true, nullable=false)
    public int getInIdtipocuenta() {
        return this.inIdtipocuenta;
    }
    
    public void setInIdtipocuenta(int inIdtipocuenta) {
        this.inIdtipocuenta = inIdtipocuenta;
    }

    
    @Column(name="VC_NOMBRETIPOCTA", nullable=false, length=30)
    public String getVcNombretipocta() {
        return this.vcNombretipocta;
    }
    
    public void setVcNombretipocta(String vcNombretipocta) {
        this.vcNombretipocta = vcNombretipocta;
    }

    
    @Column(name="VC_DESCRIPCIONTIPOCTA", length=45)
    public String getVcDescripciontipocta() {
        return this.vcDescripciontipocta;
    }
    
    public void setVcDescripciontipocta(String vcDescripciontipocta) {
        this.vcDescripciontipocta = vcDescripciontipocta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbTipocuenta")
    public Set getTbCuentas() {
        return this.tbCuentas;
    }
    
    public void setTbCuentas(Set tbCuentas) {
        this.tbCuentas = tbCuentas;
    }




}


