package com.webserver.bean;
// Generated 15-jun-2015 20:55:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbTipotransaccion generated by hbm2java
 */
@Entity
@Table(name="tb_tipotransaccion"
    ,catalog="abcdatabase"
)
public class TbTipotransaccion  implements java.io.Serializable {


     private int inIdtipotransaccion;
     private String vcNombretransaccion;
     private String vcDescripciontransaccion;
     private Set tbTransaccions = new HashSet(0);

    public TbTipotransaccion() {
    }

	
    public TbTipotransaccion(int inIdtipotransaccion) {
        this.inIdtipotransaccion = inIdtipotransaccion;
    }
    public TbTipotransaccion(int inIdtipotransaccion, String vcNombretransaccion, String vcDescripciontransaccion, Set tbTransaccions) {
       this.inIdtipotransaccion = inIdtipotransaccion;
       this.vcNombretransaccion = vcNombretransaccion;
       this.vcDescripciontransaccion = vcDescripciontransaccion;
       this.tbTransaccions = tbTransaccions;
    }
   
     @Id 

    
    @Column(name="IN_IDTIPOTRANSACCION", unique=true, nullable=false)
    public int getInIdtipotransaccion() {
        return this.inIdtipotransaccion;
    }
    
    public void setInIdtipotransaccion(int inIdtipotransaccion) {
        this.inIdtipotransaccion = inIdtipotransaccion;
    }

    
    @Column(name="VC_NOMBRETRANSACCION", length=45)
    public String getVcNombretransaccion() {
        return this.vcNombretransaccion;
    }
    
    public void setVcNombretransaccion(String vcNombretransaccion) {
        this.vcNombretransaccion = vcNombretransaccion;
    }

    
    @Column(name="VC_DESCRIPCIONTRANSACCION", length=45)
    public String getVcDescripciontransaccion() {
        return this.vcDescripciontransaccion;
    }
    
    public void setVcDescripciontransaccion(String vcDescripciontransaccion) {
        this.vcDescripciontransaccion = vcDescripciontransaccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbTipotransaccion")
    public Set getTbTransaccions() {
        return this.tbTransaccions;
    }
    
    public void setTbTransaccions(Set tbTransaccions) {
        this.tbTransaccions = tbTransaccions;
    }




}


