package com.webserver.bean;
// Generated 15-jun-2015 20:55:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbTransaccion generated by hbm2java
 */
@Entity
@Table(name="tb_transaccion"
    ,catalog="abcdatabase"
)
public class TbTransaccion  implements java.io.Serializable {


     private int inIdtransaccion;
     private TbOperacion tbOperacion;
     private TbTipotransaccion tbTipotransaccion;
     private String vcCuentadestino;
     private Date dtFechatransaccion;
     private Double doMontotransaccion;

    public TbTransaccion() {
    }

	
    public TbTransaccion(int inIdtransaccion, TbOperacion tbOperacion, TbTipotransaccion tbTipotransaccion) {
        this.inIdtransaccion = inIdtransaccion;
        this.tbOperacion = tbOperacion;
        this.tbTipotransaccion = tbTipotransaccion;
    }
    public TbTransaccion(int inIdtransaccion, TbOperacion tbOperacion, TbTipotransaccion tbTipotransaccion, String vcCuentadestino, Date dtFechatransaccion, Double doMontotransaccion) {
       this.inIdtransaccion = inIdtransaccion;
       this.tbOperacion = tbOperacion;
       this.tbTipotransaccion = tbTipotransaccion;
       this.vcCuentadestino = vcCuentadestino;
       this.dtFechatransaccion = dtFechatransaccion;
       this.doMontotransaccion = doMontotransaccion;
    }
   
     @Id 

    
    @Column(name="IN_IDTRANSACCION", unique=true, nullable=false)
    public int getInIdtransaccion() {
        return this.inIdtransaccion;
    }
    
    public void setInIdtransaccion(int inIdtransaccion) {
        this.inIdtransaccion = inIdtransaccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TB_OPERACION_IN_IDOPERACION", nullable=false)
    public TbOperacion getTbOperacion() {
        return this.tbOperacion;
    }
    
    public void setTbOperacion(TbOperacion tbOperacion) {
        this.tbOperacion = tbOperacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TB_TIPOTRANSACCION_IN_IDTIPOTRANSACCION", nullable=false)
    public TbTipotransaccion getTbTipotransaccion() {
        return this.tbTipotransaccion;
    }
    
    public void setTbTipotransaccion(TbTipotransaccion tbTipotransaccion) {
        this.tbTipotransaccion = tbTipotransaccion;
    }

    
    @Column(name="VC_CUENTADESTINO", length=45)
    public String getVcCuentadestino() {
        return this.vcCuentadestino;
    }
    
    public void setVcCuentadestino(String vcCuentadestino) {
        this.vcCuentadestino = vcCuentadestino;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FECHATRANSACCION", length=10)
    public Date getDtFechatransaccion() {
        return this.dtFechatransaccion;
    }
    
    public void setDtFechatransaccion(Date dtFechatransaccion) {
        this.dtFechatransaccion = dtFechatransaccion;
    }

    
    @Column(name="DO_MONTOTRANSACCION", precision=22, scale=0)
    public Double getDoMontotransaccion() {
        return this.doMontotransaccion;
    }
    
    public void setDoMontotransaccion(Double doMontotransaccion) {
        this.doMontotransaccion = doMontotransaccion;
    }




}


